runtime: python311

env_variables:
  DJANGO_SETTINGS_MODULE: "core.settings"
  DJANGO_DEBUG: "False"
  ALLOWED_HOSTS: ".el.r.appspot.com"
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  GS_BUCKET_NAME: ${GS_BUCKET_NAME}
  GOOGLE_CLOUD_PROJECT: ${GCP_PROJECT_ID}
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}

handlers:
- url: /static
  static_dir: staticfiles
  secure: always

- url: /.*
  script: auto
  secure: always

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

entrypoint: gunicorn -b :$PORT core.wsgi:application

beta_settings:
  cloud_sql_instances: navcode-backend:us-central1:navcode-db 