# Generated by Django 5.1.7 on 2025-03-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='dark_bg_color',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='order',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_categories/'),
        ),
    ]
