# Generated by Django 5.1.7 on 2025-03-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='read_more_link',
            field=models.URLField(blank=True, help_text='External link for more information about the service', max_length=500),
        ),
    ]
